apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.allow-http: "true"
  #    kubernetes.io/ingress.class: nginx
#    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: jenkins.bmstu.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins-service
            port:
              number: 8080

  - host: prometheus.bmstu.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus
            port:
              number: 9090

  - host: grafana.bmstu.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000

