- name: Update Package Cache (apt/Ubuntu)
  become: yes
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_distribution == "Ubuntu"

- name: install apt-transport-https, curl
  ansible.builtin.package:
    name: {{ item }}
    state: present
  with_items:
    - apt-transport-https
    - curl
