---
- name: Installing Ingress
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
    kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
    kubectl label node "{{ansible_hostname}}" ingress-ready=true  

- name: Applying everything 
  shell: |
    kubectl apply -f /tmp/deployments/node-exporter
    kubectl apply -f /tmp/deployments/prometheus
    kubectl apply -f /tmp/deployments/grafana
