---
- name: Installing Ingress
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
    kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
    kubectl label node yermastervm ingress-ready=true  

- name: Applying everything 
  shell: |
    kubectl apply -f deployments
