---
- name: Remove /etc/containerd/config.toml
  become: yes
  become_user: root
  ansible.builtin.file:
    path: /etc/containerd/config.toml
    state: absent

- name: Restart containerd
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: containerd

- name: Initialize the cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

    #- name: Install ACL
    #  apt:
    #    name: 'acl'
    #    update_cache: yes
    #    cache_valid_time: '{{ 60 * 60 * 24 }}'

- name: Create .kube directory
  become: yes
  become_user: root
  file:
    path: /home/kube/.kube
    state: directory
    mode: 0755

- name: Copies admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/kube/.kube/config
    remote_src: yes
    owner: kube

- name: Create a symbolic link
  become: true
  become_user: root
  ansible.builtin.template:
    src: "{{playbook_dir}}/../cluster_config/calico.yaml"
    dest: /tmp/calico.yaml

- name: Install Pod network
  become: yes
  become_user: kube
  shell: kubectl apply -f /tmp/calico.yaml 
  args:
    chdir: $HOME
    
- name: Get the token for joining the worker nodes
  become: yes
  become_user: kube
  shell: kubeadm token create  --print-join-command
  register: kubernetes_join_command

- name: Output
  debug:
    msg: "{{ kubernetes_join_command.stdout }}"

- name: Copy join command to local file.
  become: False
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command"

- name: Enable Master node for deploying 
  become: yes
  become_user: kube
  shell: kubectl taint node {{ansible_hostname}} node-role.kubernetes.io/control-plane:NoSchedule-

