---
- name: Update Package Cache (apt/Ubuntu)
  become: yes
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_distribution == "Ubuntu"

- name: disable swap
  shell: |
          sudo swapoff -a
          sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: Add google key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg 
    state: present

- name: Create kubernetes repo file
  file:
    path: "/etc/apt/sources.list.d/kubernetes.list"
    state: "touch"

- name: Add K8s Source
  blockinfile:
    path: "/etc/apt/sources.list.d/kubernetes.list"
    block: |
          deb https://apt.kubernetes.io/ kubernetes-xenial main

- name: install kubernetes
  ansible.builtin.package:
    state: present
    name:
      - kubeadm=1.26.0-00
      - kubectl=1.26.0-00
      - kubelet=1.26.0-00

- name: Hold kubeadm
    ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubeadm
    - kubectl
    - kubelet
