apiVersion: v1
kind: ConfigMap
metadata:
  name: datasource-config
  namespace: kube-system
data:
  datasource.yaml: |-
        apiVersion: 1

        datasources:
          - name: Prometheus
            type: prometheus
            # Access mode - proxy (server in the UI) or direct (browser in the UI).
            access: proxy
            url: http://prometheus.kube-system.svc.cluster.local:9090
            jsonData:
              httpMethod: POST
              manageAlerts: true
              prometheusType: Prometheus
              prometheusVersion: 2.42.0

