---
- name: Create containerd config file
  file:
    path: "/etc/modules-load.d/containerd.conf"
    state: "touch"

- name: Add conf for containerd
  blockinfile:
    path: "/etc/modules-load.d/containerd.conf"
    block: |
          overlay
          br_netfilter

- name: Load overlay and br_netfilter kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter


- name: Set system configurations for Kubernetes networking
  file:
    path: "/etc/sysctl.d/99-kubernetes-cri.conf"
    state: "touch"

- name: Add conf for containerd
  blockinfile:
    path: "/etc/sysctl.d/99-kubernetes-cri.conf"
    block: |
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-ip6tables = 1

- name: Apply new settings
  command: sudo sysctl --system

- name: Update Package Cache (apt/Ubuntu)
  become: yes
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_distribution == "Ubuntu"

- name: install containerd
  ansible.builtin.package:
#    name: containerd.io
    name: containerd
    state: present

- name: Create /etc/containerd
  become: yes
  file:
    path: /etc/containerd
    state: directory
    mode: 0755

- name: Restart containerd
  ansible.builtin.systemd:
    state: restarted
    name: containerd
